### ISSUE TITLE
Exception when running against https://github.com/thoughtbot/clearance

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli#15]
To reproduce, run the following in a Jupyter notebook.

```csharp

using XPlot.Plotly;

using LibMetrics;
using LibMetrics.Languages.Ruby;
using LibMetrics.Languages.Php;

ManifestFinder.Register<RubyBundlerManifestFinder>();
ManifestFinder.Register<PhpComposerManifestFinder>();

FileHistoryFinder.Register<GitFileHistoryFinder>();

var runner = new Runner();

var projects = new Dictionary<string, IList<MetricsResult>>();
projects["libmetrics-fixture-ruby-nokotest"] = runner.Run("https://github.com/corgibytes/libmetrics-fixture-ruby-nokotest");
projects["clearance"] = runner.Run("https://github.com/thoughtbot/clearance");

var series = projects.Select(p => new Graph.Scattergl { 
  name = p.Key, 
  x = p.Value.Select(r => r.Date),
  y = p.Value.Select(r => r.LibYear.Total)
});

var chart = Chart.Plot(series.ToArray());
chart.WithTitle("LibYear over time");
display(chart)
```

Exception output:

```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at LibMetrics.Languages.Ruby.RubyGemsRepository.LatestAsOf(DateTime date, String name)
   at LibMetrics.LibYearCalculator.ComputeAsOf(DateTime date)
   at LibMetrics.Runner.Run(String analysisPath, DateTime asOf)
   at LibMetrics.Runner.Run(String analysisPath)
   at Submission#11.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at LibMetrics.Languages.Ruby.RubyGemsRepository.LatestAsOf(DateTime date, String name)
   at LibMetrics.LibYearCalculator.ComputeAsOf(DateTime date)
   at LibMetrics.Runner.Run(String analysisPath, DateTime asOf)
   at LibMetrics.Runner.Run(String analysisPath)
   at Submission#11.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

This also appears to be happening when running against other repositories as well.

**Comment by nickiemc** [comment]
The only remaining issues will be resolved by #153. Marking as closed.
