### ISSUE TITLE
Exception when running against: `https://github.com/mailpile/Mailpile`

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli#28]
Exception from Jupyter Notebook:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Freshli.Languages.Python.PyPIRepository.<>c__DisplayClass4_0.<Latest>b__2(VersionInfo v)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Freshli.Languages.Python.PyPIRepository.Latest(String name, String thatMatches, DateTime asOf)
   at Freshli.LibYearCalculator.ComputeAsOf(DateTime date)
   at Freshli.Runner.Run(String analysisPath, DateTime asOf)
   at Freshli.Runner.Run(String analysisPath)
   at Submission#18.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Freshli.Languages.Python.PyPIRepository.<>c__DisplayClass4_0.<Latest>b__2(VersionInfo v)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Freshli.Languages.Python.PyPIRepository.Latest(String name, String thatMatches, DateTime asOf)
   at Freshli.LibYearCalculator.ComputeAsOf(DateTime date)
   at Freshli.Runner.Run(String analysisPath, DateTime asOf)
   at Freshli.Runner.Run(String analysisPath)
   at Submission#18.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

**Comment by nickiemc** [comment]
The following issues are occurring (when running against [113-add-python-specific-version-info](https://github.com/corgibytes/freshli/tree/113-add-python-specific-version-info)): 

***

1. `PythonVersionInfo` is unable to parse the following [line](https://github.com/mailpile/Mailpile/blob/65f096f1c645f311fc030364c32a1890c9beac03/requirements.txt#L2): 
  `http://sourceforge.net/projects/py-gnupg/files/GnuPGInterface/0.3.2/GnuPGInterface-0.3.2.tar.gz`

The package name is returned as `http`. 

***

2. `PythonVersionInfo` is unable to parse the following [line](https://github.com/mailpile/Mailpile/blob/0a1f27e7a6d470d75bd535b0a91bd7fad01ca794/requirements.txt#L3): 
  `git+https://github.com/mitsuhiko/jinja2.git#egg=Jinja2`

The package name is returned as `git`. 

***

3. `PythonVersionInfo` is unable find the latest version of the following dependencies:
  [`spambayes==1.1b1`](https://github.com/mailpile/Mailpile/blob/5af50d03eb0d7eea61987fcca9264908b79602ce/requirements.txt#L3) 
  [`spambayes>=1.1b1`](https://github.com/mailpile/Mailpile/blob/9437d7c9b5fd82326961eaeda05f16daf7700d2b/requirements.txt#L3) 

Per the [release history](https://pypi.org/project/spambayes/#history), these should be valid releases.

***

**Comment by nickiemc** [comment]
The first two issues are logged as #160. The third issue is logged as #161.

No other issues remain. Marking as closed.
