### ISSUE TITLE
Exception when running against: `https://github.com/matterport/Mask_RCNN`

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli#29]
From Jupyter Notebook:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Freshli.Languages.Python.PyPIRepository.<>c__DisplayClass4_0.<Latest>b__2(VersionInfo v)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Freshli.Languages.Python.PyPIRepository.Latest(String name, String thatMatches, DateTime asOf)
   at Freshli.LibYearCalculator.ComputeAsOf(DateTime date)
   at Freshli.Runner.Run(String analysisPath, DateTime asOf)
   at Freshli.Runner.Run(String analysisPath)
   at Submission#19.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Freshli.Languages.Python.PyPIRepository.<>c__DisplayClass4_0.<Latest>b__2(VersionInfo v)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Freshli.Languages.Python.PyPIRepository.Latest(String name, String thatMatches, DateTime asOf)
   at Freshli.LibYearCalculator.ComputeAsOf(DateTime date)
   at Freshli.Runner.Run(String analysisPath, DateTime asOf)
   at Freshli.Runner.Run(String analysisPath)
   at Submission#19.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

**Comment by nickiemc** [comment]
I successfully re-ran using the latest code.

A minor remaining issue was logged as #118.
